export const MEDICATIONS = [
  {
    id: 1,
    name: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    doctor: "Dr. John Smith",
    pharmacy: "ABC Pharmacy",
    nextRefillDate: "2024-02-28",
    notes: "Take with meals to avoid stomach upset.",
  },
  {
    id: 2,
    name: "Simvastatin",
    dosage: "20mg",
    frequency: "Once daily",
    doctor: "Dr. Jane Doe",
    pharmacy: "DEF Pharmacy",
    nextRefillDate: "2024-03-15",
    notes: "Avoid grapefruit while taking this medication.",
  },
  {
    id: 3,
    name: "Albuterol inhaler",
    dosage: "2 puffs as needed",
    frequency: "N/A",
    doctor: "Dr. Michael Jones",
    pharmacy: "GHI Pharmacy",
    nextRefillDate: null,
    notes: "Use for shortness of breath or wheezing.",
  },
  {
    id: 4,
    name: "Levothyroxine",
    dosage: "0.1mg",
    frequency: "Once daily",
    doctor: "Dr. Sarah Lee",
    pharmacy: "JKL Pharmacy",
    nextRefillDate: "2024-04-10",
    notes: "Take on an empty stomach, first thing in the morning.",
  },
  // Add more medication objects as needed
];
