import { v4 as uuidv4 } from "uuid";
import { ROLES } from "../../constants";
export const USERS = [
  {
    id: uuidv4(),
    name: "Alice",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "alice@example.com",
    role: ROLES.PATIENT,
  },
  {
    id: uuidv4(),
    name: "Bob",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "bob@example.com",
    role: ROLES.HEALTH_ADMINISTRATOR,
  },
  {
    id: uuidv4(),
    name: "Charlie",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "charlie@example.com",
    role: ROLES.PHARMACIST,
  },
  {
    id: uuidv4(),
    name: "David",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "david@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Eva",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "eva@example.com",
    role: ROLES.PATIENT,
  },
  {
    id: uuidv4(),
    name: "Frank",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "frank@example.com",
    role: ROLES.HEALTH_ADMINISTRATOR,
  },
  {
    id: uuidv4(),
    name: "Grace",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "grace@example.com",
    role: ROLES.PHARMACIST,
  },
  {
    id: uuidv4(),
    name: "Henry",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "henry@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Ivy",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "ivy@example.com",
    role: ROLES.PATIENT,
  },
  {
    id: uuidv4(),
    name: "Jack",
    activated: false,
    deactivated: false,
    deleted: false,
    email: "jack@example.com",
    role: ROLES.HEALTH_ADMINISTRATOR,
  },
];
