export const ACTIVE_PRESCRITIONS = [
  {
    id: 1,
    medication: "Aspirin",
    dosage: "100mg",
    frequency: "Twice daily",
    duration: "10 days",
    doctor: "Dr. Smith",
    datePrescribed: "2024-02-14",
    remainderSet: false,
  },
  {
    id: 2,
    medication: "Ibuprofen",
    dosage: "200mg",
    frequency: "Once daily",
    duration: "7 days",
    doctor: "Dr. Johnson",
    datePrescribed: "2024-02-15",
    remainderSet: false,
  },
  {
    id: 3,
    medication: "Paracetamol",
    dosage: "500mg",
    frequency: "Three times daily",
    duration: "5 days",
    doctor: "Dr. Lee",
    datePrescribed: "2024-02-16",
    remainderSet: false,
  },
  {
    id: 4,
    medication: "Amoxicillin",
    dosage: "250mg",
    frequency: "Once daily",
    duration: "14 days",
    doctor: "Dr. Wilson",
    datePrescribed: "2024-02-17",
    remainderSet: false,
  },
  {
    id: 5,
    medication: "Loratadine",
    dosage: "10mg",
    frequency: "Once daily",
    duration: "7 days",
    doctor: "Dr. Brown",
    datePrescribed: "2024-02-18",
    remainderSet: false,
  },
  {
    id: 6,
    medication: "Omeprazole",
    dosage: "20mg",
    frequency: "Once daily",
    duration: "30 days",
    doctor: "Dr. Patel",
    datePrescribed: "2024-02-19",
    remainderSet: false,
  },
  {
    id: 7,
    medication: "Prednisone",
    dosage: "5mg",
    frequency: "Twice daily",
    duration: "10 days",
    doctor: "Dr. Garcia",
    datePrescribed: "2024-02-20",
    remainderSet: false,
  },
  {
    id: 8,
    medication: "Simvastatin",
    dosage: "40mg",
    frequency: "Once daily",
    duration: "90 days",
    doctor: "Dr. Martinez",
    datePrescribed: "2024-02-21",
    remainderSet: false,
  },
  {
    id: 9,
    medication: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    duration: "30 days",
    doctor: "Dr. Taylor",
    datePrescribed: "2024-02-22",
    remainderSet: false,
  },
  {
    id: 10,
    medication: "Ciprofloxacin",
    dosage: "250mg",
    frequency: "Once daily",
    duration: "7 days",
    doctor: "Dr. Adams",
    datePrescribed: "2024-02-23",
    remainderSet: false,
  },
  {
    id: 11,
    medication: "Diazepam",
    dosage: "5mg",
    frequency: "As needed",
    duration: "N/A",
    doctor: "Dr. Scott",
    datePrescribed: "2024-02-24",
    remainderSet: false,
  },
  {
    id: 12,
    medication: "Warfarin",
    dosage: "2mg",
    frequency: "Once daily",
    duration: "Indefinite",
    doctor: "Dr. Thomas",
    datePrescribed: "2024-02-25",
    remainderSet: false,
  },
];
