import { v4 as uuidv4 } from "uuid";
import { ROLES } from "../../../constants";
export const HEALTHCARE_PROVIDERS = [
  {
    id: uuidv4(),
    name: "Alice",
    deleted: false,
    mobile: "730483903",
    email: "alice@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Bob",
    deleted: false,
    mobile: "730483903",
    email: "bob@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Charlie",
    deleted: false,
    mobile: "730483903",
    email: "charlie@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "David",
    deleted: false,
    mobile: "730483903",
    email: "david@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Eva",
    deleted: false,
    mobile: "730483903",
    email: "eva@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Frank",
    deleted: false,
    mobile: "730483903",
    email: "frank@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Grace",
    deleted: false,
    mobile: "730483903",
    email: "grace@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Henry",
    deleted: false,
    mobile: "730483903",
    email: "henry@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Ivy",
    deleted: false,
    mobile: "730483903",
    email: "ivy@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
  {
    id: uuidv4(),
    name: "Jack",
    deleted: false,
    mobile: "730483903",
    email: "jack@example.com",
    role: ROLES.HEALTHCARE_PROVIDERS,
  },
];
